### ISSUE TITLE
Version 13 deprecated

### ISSUE THREAD

**Issue by dominikraff** [joelbutcher/googleads#7]
Hello.
can you change to v15 in your GoogleAds.php File?
public function __construct(
private string $clientId,
private string $clientSecret,
private string $developerToken,
private int $sdkVersion = SupportedVersions::VERSION_13,
private string $transportProtocol = 'rest',
private ?LoggerInterface $logger = null,
private string $logLevel = 'INFO'
)

**Comment by joelbutcher** [comment]
Fixed with [v8.0.0](https://github.com/joelbutcher/googleads/releases/tag/v8.0.0)

**Comment by joelbutcher** [comment]
Will update the laravel wrapper this evening.
